<?php connexion($bd_server,$bd_user,$bd_passwd,$bd_base_ceg); ?>


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Strict//EN">
<html xml:lang="fr" xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>/X\ CEG - Manager /X\</title>
	<meta http-equiv=content-type content="text/html; charset=iso-8859-1">
	<meta http-equiv=content-script-type content=text/javascript>
	<meta http-equiv=content-style-type content=text/css>
	<meta content="internet" name=category>
	<meta content="index, follow" name=robots>
	<link title=normal media=screen href="http://www.lc78-escrime.com/V2/manager/style/style.css" type=text/css rel=stylesheet>
	<!--<link href="../style/logo_grad.ico" type=images/x-icon rel="shortcut icon">-->
	<meta content="mshtml 6.00.2800.1491" name=generator>
</head>

<body>
	<div id="topnav">
		<ul>
			<li><a href="http://www.lc78-escrime.com/V2/manager/index.php">Accueil</a></li>
			<li><a href="http://www.lc78-escrime.com/V2/manager/tireurs/search_tireurs.php">Tireurs</a></li>
			<li><a href="#">Présence</a></li>
			<li><a href="http://www.lc78-escrime.com/V2/manager/competition/index.php">Compétitions</a></li>
			<li><a href="http://www.lc78-escrime.com/V2/manager/compte/view.php">Mon compte</a></li>
			<li><a href="http://www.lc78-escrime.com/V2/manager/admin/index.php">Admnistration</a></li>
			<li><a href="#" onClick="window.open('http://www.lc78-escrime.com/V2/manager/apropos.php','A propos','width=426','height=420')">A propos</a></li>
		</ul>
	</div>