<?php mysql_close($connexion);?>
		
			<div id="footer">
				<p>
					<a href="mailto:thomas.raso@lc78-escrime.com?subject=LC78">Réalisation T. Raso</a>
				</p>
				<!--<p>
					DRAFT VERSION
				</p>-->
				<p>
					<a href="http://www.lc78-escrime.com/index.php" target="_blank">LC78 Escrime</a>
				</p>
				<p>
					<a href="http://jupiter.lc78-escrime.com/">JUPITER</a>
				</p>
		</div>
	</div>

</body>
</html>