<?php connexion($bd_server,$bd_user,$bd_passwd,$bd_base_ceg); ?>


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Strict//EN">
<html xml:lang="fr" xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>LC78 - JUPITER</title>
	<meta http-equiv=content-type content="text/html; charset=iso-8859-1">
	<meta http-equiv=content-script-type content=text/javascript>
	<meta http-equiv=content-style-type content=text/css>
	<meta content="internet" name=category>
	<meta content="index, follow" name=robots>
	<link title=normal media=screen href="http://<?php echo $hostname; ?>/JUPITER/style/style.css" type=text/css rel=stylesheet>
	<link href="http://<?php echo $hostname; ?>/JUPITER/style/logo_LC78.jpeg" type=images/x-icon rel="shortcut icon">
	<meta content="mshtml 6.00.2800.1491" name=generator>
</head>

<body>
	<div id="topnav">
		<ul>
			<li><a href="http://<?php echo $hostname; ?>/JUPITER/index.php">Accueil</a></li>
			<li><a href="http://<?php echo $hostname; ?>/JUPITER/tireurs/search_tireurs.php">Tireurs</a></li>
			<li><a href="#">Présence</a></li>
			<li><a href="http://<?php echo $hostname; ?>/JUPITER/competition/index.php">Compétitions</a></li>
			<li><a href="http://<?php echo $hostname; ?>/JUPITER/compte/view.php">Mon compte</a></li>
			<li><a href="http://<?php echo $hostname; ?>/JUPITER/admin/index.php">Administration</a></li>
			<!--<li><a href="#" onClick="window.open('http://<?php echo $hostname; ?>/JUPITER/apropos.php','A propos')">A propos</a></li>-->
		</ul>
	</div>